artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1-6V-m17-kFtFe5HP_vS_RbIqU3NV9_qL/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["image.png", "video.mp4"]


posfinder:
  root_dir: artifacts/posfinder
  image_dir: artifacts/data_ingestion/data/image.png
  pickle_dir: artifacts/posfinder/carparkpos



parking_counter:
  root_dir: artifacts/parking_counter
  pickle_dir: artifacts/posfinder/carparkpos
  video_dir: artifacts/data_ingestion/data/video.mp4
  video_write_dir: artifacts/posfinder/output



# data_source:
#   video_source: /Image_Video/video.mp4
#   image_source: /Image_Video/image.jpg